app = "cossyreign-developed-bot"
primary_region = "jnb"

[build]

[env]
  NODE_ENV = "production"
  PREFIX = "."

[[mounts]]
  source = "sessions"
  destination = "/app/sessions"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "node connect.js" 
